libchannel: libchannel
libchannel
libchannel provides an abstraction around communication channels like sockets.
Data Structures
struct channel
A communications channel for sending data and capabilities (eg file descriptors and channels).
Functions
struct channel * channel_create (int flags)
Create a channel with certain properties.
bool channel_isvalid (struct channel *)
Tests the validity of a pointer that claims to be a channel.
void channel_destroy (struct channel *c)
Free a channel.
int channel_flags (struct channel *)
Get a channel's flags.
int channel_descriptor (struct channel *)
A file descriptor representation of a channel.
Detailed Description
libchannel provides an abstraction around communication channels like sockets.
This allows a message-passing style of interaction, whether the backend is a socket or a function call in the same address space.
Function Documentation
struct channel* channel_create (int flags) read
Create a channel with certain properties.
Parameters
flags any of a number of flags OR'ed together:
CHANNEL_RELIABLE: guarantee reliable delivery
CHANNEL_INORDER: guarantee in-order delivery
Definition at line 40 of file libchannel.c.
{
        // TODO: choose among UDS, something else?
        return uds_wrap(uds_create(flags));
}
int channel_descriptor (struct channel *)
A file descriptor representation of a channel.
This descriptor can be polled, selected, etc.
Definition at line 73 of file libchannel.c.
References channel_isvalid().
{
        if (!channel_isvalid(c)) return -1;
        return c->get_descriptor(c);
}
void channel_destroy (struct channel * c)
Free a channel.
Parameters
c must be a channel or NULL
Definition at line 59 of file libchannel.c.
References channel_isvalid().
{
        assert(channel_isvalid(c));
        free(c);
}
int channel_flags (struct channel *)
Get a channel's flags.
These flags cannot be changed after creation, but they can be retrieved.
Returns
-1 on error, OR'ed combination of flags otherwise
Definition at line 66 of file libchannel.c.
References channel_isvalid().
{
        if (!channel_isvalid(c)) return -1;
        return c->flags;
}
bool channel_isvalid (struct channel *)
Tests the validity of a pointer that claims to be a channel.
Definition at line 47 of file libchannel.c.
Referenced by channel_descriptor(), channel_destroy(), and channel_flags().
{
        if (c == NULL) return false;
        if (c->get_descriptor == NULL) return false;
        // As we implement other kinds of channels, add more magic tests here.
        if (c->magic == UDS_MAGIC) return true;
        return false;
}